name = "Solidity"
grammar = "solidity"
path_suffixes = ["sol"]
first_line_pattern = "^\\s*pragma\\s+solidity"
line_comments = ["// "]
block_comments = ["/*", "*/"]
brackets = [
    { start = "{", end = "}", completion = true, newline = true },
    { start = "[", end = "]", completion = true, newline = true },
    { start = "(", end = ")", completion = true, newline = true },
    { start = "\"", end = "\"", completion = true, newline = false },
    { start = "'", end = "'", completion = true, newline = false },
]
word_characters = ["_", "$"]
tab_size = 4
hard_tabs = false

[language_servers.solidity]
name = "Solidity Language Server"
languages = ["Solidity"]
