id = "web3"
name = "Web3"
version = "0.0.1"
schema_version = 1
authors = ["Demion La <pradovd4@gmail.com>"]
description = "Web3 development support with Solidity, Hardhat, and Foundry integration"
repository = "https://github.com/Demion-L/web3-zed"

[grammars.solidity]
repository = "https://github.com/JoranHonig/tree-sitter-solidity"
rev = "9e963f739ca341209aff2175b5beb9c1749c578e"
