name = "Hardhat Config"
grammar = "javascript"
file_types = ["hardhat.config.js", "hardhat.config.ts"]
line_comments = ["// "]
word_characters = ["_", "$"]
tab_size = 2
hard_tabs = false
indent_units = 2

# Smart indentation for JS/TS configs
indent_patterns = [{ match = "^\\s*(\\{|\\()", until = "^\\s*(\\}|\\))" }]

# Brackets (keep your existing setup)
brackets = [
    { start = "{", end = "}", completion = true, newline = true },
    { start = "[", end = "]", completion = true, newline = true },
    { start = "(", end = ")", completion = true, newline = true },
    { start = "\"", end = "\"", completion = true, newline = false },
    { start = "'", end = "'", completion = true, newline = false },
    { start = "`", end = "`", completion = true, newline = false },
]

# Future LSP support
[language]
completion_triggers = [
    { trigger = "config.", completions = [
        "networks",
        "solidity",
        "paths",
    ] },
]
