name = "Foundry"
path_suffixes = ["foundry.toml"]
scope = "source.toml"
tree_sitter_library = "tree-sitter-toml"
highlights = "highlights.scm"
indent = { tab_width = 2, unit = "  " }
line = "#"
brackets = [
    { start = "{", end = "}", scope = "punctuation.bracket" },
    { start = "[", end = "]", scope = "punctuation.bracket" },
    { start = "(", end = ")", scope = "punctuation.bracket" },
]
